[workspace]
channels = ["conda-forge"]
name = "SAM_muggled_env"
platforms = ["linux-64", "win-64"]

[tasks]

[dependencies]
python = "3.12.*"
appose = "*"

[target.win-64.dependencies]
numpy = ">=1.26,<2"


[pypi-dependencies]
muggled_sam = { git = "https://github.com/heyoeyo/muggled_sam.git"}
