[workspace]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "sam3-detection-image-hg"
platforms = ["linux-64", "win-64"]

[tasks]

[dependencies]
python = "3.11.*"
appose = "*"

pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
torchaudio = { version = "*", channel = "pytorch" }
numpy = ">=1.26,<2"

[pypi-dependencies]
sam3 = { git = "https://github.com/facebookresearch/sam3.git", rev = "86ed770" }
transformers = ">=5.5.4, <6"
accelerate = ">=1.13.0, <2"
kernels = ">=0.13.0, <0.14"