[workspace]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "SAM3_env_test01"
platforms = ["linux-64", "win-64"]

[tasks]

[dependencies]

python = "3.11.*"
setuptools = "<82"
appose = "*"


pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
torchaudio = { version = "*", channel = "pytorch" }
opencv = "*"
numpy = ">=1.26,<2"
matplotlib = "*"
libstdcxx-ng = "*"
pillow = "*"
einops = "*"
pycocotools = "*"
psutil = "*"
pandas = "*"
scikit-image = "*"
scikit-learn = "*"

[pypi-dependencies]
sam3 = { git = "https://github.com/facebookresearch/sam3.git" }
decord = "*"

