# --- Tasks ---
# Available Tasks
task.ids=classification,semanticSegmentation,detection,instanceSegmentation,denoising

# --- Task-Model Relationships ---
# Which models are available for each task
classification.model.ids=rf,mlp,cnn
semanticSegmentation.model.ids=rf,mlp,unet,yolo
detection.model.ids=yolo,detr
instanceSegmentation.model.ids=unet,yolo
denoising.model.ids=unet

# --- Models (Architectures) ---
# Available Models
model.ids=rf,mlp,cnn,unet,yolo,detr

# --- Model-Task Relationships ---
# Which tasks can be performed by each model
rf.task.ids=classification,semanticSegmentation
mlp.task.ids=classification,semanticSegmentation
cnn.task.ids=classification
unet.task.ids=semanticSegmentation,instanceSegmentation,denoising
yolo.task.ids=detection,instanceSegmentation,semanticSegmentation
detr.task.ids=detection

# --- Runnable Examples ---
# For each task/model pair, list the available, configured examples
# Keys are structured as: run.[task_id].[model_id].[property]

# Classification with RandomForest
run.classification.rf.runnable=false

# Classification with MLP
run.classification.mlp.runnable=true
run.classification.mlp.examples.ids=mlp-histo-cells

# Classification with CNN
run.classification.cnn.runnable=true
run.classification.cnn.examples.ids=cnn-histo-cells,cnn-mnist

# Semantic segmentation with Random Forest
run.semanticSegmentation.rf.runnable=true
run.semanticSegmentation.rf.examples.ids=rf-weka-renal

# Semantic segmentation with MLP
run.semanticSegmentation.mlp.runnable=false

# Semantic segmentation with UNET
run.semanticSegmentation.unet.runnable=true
run.semanticSegmentation.unet.examples.ids=unet-mito-seg

# Semantic Segmentation with YOLO
run.semanticSegmentation.yolo.runnable=true
run.semanticSegmentation.yolo.examples.ids=yolo-cell-nuclei_semantic

# Detection with YOLO
run.detection.yolo.runnable=true
run.detection.yolo.examples.ids=yolo-cell-nuclei_detec

# Detection with DETR
run.detection.detr.runnable=false

# Instance Segmentation with UNET
run.instanceSegmentation.unet.runnable=true
run.instanceSegmentation.unet.examples.ids=unet-nucleus-seg,unet-subtilis-seg

# Instance Segmentation with YOLO
run.instanceSegmentation.yolo.runnable=true
run.instanceSegmentation.yolo.examples.ids=yolo-cell-nuclei_instance

# Denoising with UNET
run.denoising.unet.runnable=true
run.denoising.unet.examples.ids=unet-n2v-cells